name: VAMPIRE
main: de.nexxus.vampire.main.Main
version: 1.0



commands:
  setup:
    description: setup the game
  state:
    description: starts a gamestate
  join:
    description: Joins a team (survivor, vampire, spec, spectator)

  build:
    description: switchs the build mode